// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final FunctionDescriptor plist_get_uint_val$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_get_uint_val$MH = RuntimeHelper.downcallHandle(
        "plist_get_uint_val",
        constants$24.plist_get_uint_val$FUNC
    );
    static final FunctionDescriptor plist_get_int_val$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_get_int_val$MH = RuntimeHelper.downcallHandle(
        "plist_get_int_val",
        constants$24.plist_get_int_val$FUNC
    );
    static final FunctionDescriptor plist_get_real_val$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_get_real_val$MH = RuntimeHelper.downcallHandle(
        "plist_get_real_val",
        constants$24.plist_get_real_val$FUNC
    );
    static final FunctionDescriptor plist_get_data_val$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_get_data_val$MH = RuntimeHelper.downcallHandle(
        "plist_get_data_val",
        constants$24.plist_get_data_val$FUNC
    );
    static final FunctionDescriptor plist_get_data_ptr$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_get_data_ptr$MH = RuntimeHelper.downcallHandle(
        "plist_get_data_ptr",
        constants$24.plist_get_data_ptr$FUNC
    );
    static final FunctionDescriptor plist_get_date_val$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_get_date_val$MH = RuntimeHelper.downcallHandle(
        "plist_get_date_val",
        constants$24.plist_get_date_val$FUNC
    );
}


