// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final FunctionDescriptor plist_string_val_compare_with_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle plist_string_val_compare_with_size$MH = RuntimeHelper.downcallHandle(
        "plist_string_val_compare_with_size",
        constants$31.plist_string_val_compare_with_size$FUNC
    );
    static final FunctionDescriptor plist_string_val_contains$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_string_val_contains$MH = RuntimeHelper.downcallHandle(
        "plist_string_val_contains",
        constants$31.plist_string_val_contains$FUNC
    );
    static final FunctionDescriptor plist_key_val_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_key_val_compare$MH = RuntimeHelper.downcallHandle(
        "plist_key_val_compare",
        constants$31.plist_key_val_compare$FUNC
    );
    static final FunctionDescriptor plist_key_val_compare_with_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle plist_key_val_compare_with_size$MH = RuntimeHelper.downcallHandle(
        "plist_key_val_compare_with_size",
        constants$31.plist_key_val_compare_with_size$FUNC
    );
    static final FunctionDescriptor plist_key_val_contains$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_key_val_contains$MH = RuntimeHelper.downcallHandle(
        "plist_key_val_contains",
        constants$31.plist_key_val_contains$FUNC
    );
    static final FunctionDescriptor plist_data_val_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle plist_data_val_compare$MH = RuntimeHelper.downcallHandle(
        "plist_data_val_compare",
        constants$31.plist_data_val_compare$FUNC
    );
}


