// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final FunctionDescriptor plist_array_get_item$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_array_get_item$MH = RuntimeHelper.downcallHandle(
        "plist_array_get_item",
        constants$20.plist_array_get_item$FUNC
    );
    static final FunctionDescriptor plist_array_get_item_index$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_array_get_item_index$MH = RuntimeHelper.downcallHandle(
        "plist_array_get_item_index",
        constants$20.plist_array_get_item_index$FUNC
    );
    static final FunctionDescriptor plist_array_set_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_array_set_item$MH = RuntimeHelper.downcallHandle(
        "plist_array_set_item",
        constants$20.plist_array_set_item$FUNC
    );
    static final FunctionDescriptor plist_array_append_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_array_append_item$MH = RuntimeHelper.downcallHandle(
        "plist_array_append_item",
        constants$20.plist_array_append_item$FUNC
    );
    static final FunctionDescriptor plist_array_insert_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_array_insert_item$MH = RuntimeHelper.downcallHandle(
        "plist_array_insert_item",
        constants$20.plist_array_insert_item$FUNC
    );
    static final FunctionDescriptor plist_array_remove_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_array_remove_item$MH = RuntimeHelper.downcallHandle(
        "plist_array_remove_item",
        constants$20.plist_array_remove_item$FUNC
    );
}


