// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final FunctionDescriptor plist_from_memory$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_from_memory$MH = RuntimeHelper.downcallHandle(
        "plist_from_memory",
        constants$28.plist_from_memory$FUNC
    );
    static final FunctionDescriptor plist_read_from_file$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_read_from_file$MH = RuntimeHelper.downcallHandle(
        "plist_read_from_file",
        constants$28.plist_read_from_file$FUNC
    );
    static final FunctionDescriptor plist_write_to_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_write_to_string$MH = RuntimeHelper.downcallHandle(
        "plist_write_to_string",
        constants$28.plist_write_to_string$FUNC
    );
    static final FunctionDescriptor plist_write_to_stream$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_write_to_stream$MH = RuntimeHelper.downcallHandle(
        "plist_write_to_stream",
        constants$28.plist_write_to_stream$FUNC
    );
    static final FunctionDescriptor plist_write_to_file$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_write_to_file$MH = RuntimeHelper.downcallHandle(
        "plist_write_to_file",
        constants$28.plist_write_to_file$FUNC
    );
    static final FunctionDescriptor plist_print$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_print$MH = RuntimeHelper.downcallHandle(
        "plist_print",
        constants$28.plist_print$FUNC
    );
}


