// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$30 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$30() {}
    static final FunctionDescriptor plist_int_val_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle plist_int_val_compare$MH = RuntimeHelper.downcallHandle(
        "plist_int_val_compare",
        constants$30.plist_int_val_compare$FUNC
    );
    static final FunctionDescriptor plist_uint_val_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle plist_uint_val_compare$MH = RuntimeHelper.downcallHandle(
        "plist_uint_val_compare",
        constants$30.plist_uint_val_compare$FUNC
    );
    static final FunctionDescriptor plist_uid_val_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle plist_uid_val_compare$MH = RuntimeHelper.downcallHandle(
        "plist_uid_val_compare",
        constants$30.plist_uid_val_compare$FUNC
    );
    static final FunctionDescriptor plist_real_val_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle plist_real_val_compare$MH = RuntimeHelper.downcallHandle(
        "plist_real_val_compare",
        constants$30.plist_real_val_compare$FUNC
    );
    static final FunctionDescriptor plist_date_val_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_date_val_compare$MH = RuntimeHelper.downcallHandle(
        "plist_date_val_compare",
        constants$30.plist_date_val_compare$FUNC
    );
    static final FunctionDescriptor plist_string_val_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_string_val_compare$MH = RuntimeHelper.downcallHandle(
        "plist_string_val_compare",
        constants$30.plist_string_val_compare$FUNC
    );
}


