// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final FunctionDescriptor plist_new_date$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_new_date$MH = RuntimeHelper.downcallHandle(
        "plist_new_date",
        constants$19.plist_new_date$FUNC
    );
    static final FunctionDescriptor plist_new_uid$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle plist_new_uid$MH = RuntimeHelper.downcallHandle(
        "plist_new_uid",
        constants$19.plist_new_uid$FUNC
    );
    static final FunctionDescriptor plist_new_null$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle plist_new_null$MH = RuntimeHelper.downcallHandle(
        "plist_new_null",
        constants$19.plist_new_null$FUNC
    );
    static final FunctionDescriptor plist_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_free$MH = RuntimeHelper.downcallHandle(
        "plist_free",
        constants$19.plist_free$FUNC
    );
    static final FunctionDescriptor plist_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_copy$MH = RuntimeHelper.downcallHandle(
        "plist_copy",
        constants$19.plist_copy$FUNC
    );
    static final FunctionDescriptor plist_array_get_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_array_get_size$MH = RuntimeHelper.downcallHandle(
        "plist_array_get_size",
        constants$19.plist_array_get_size$FUNC
    );
}


