// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final FunctionDescriptor plist_to_json$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_to_json$MH = RuntimeHelper.downcallHandle(
        "plist_to_json",
        constants$27.plist_to_json$FUNC
    );
    static final FunctionDescriptor plist_to_openstep$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle plist_to_openstep$MH = RuntimeHelper.downcallHandle(
        "plist_to_openstep",
        constants$27.plist_to_openstep$FUNC
    );
    static final FunctionDescriptor plist_from_xml$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_from_xml$MH = RuntimeHelper.downcallHandle(
        "plist_from_xml",
        constants$27.plist_from_xml$FUNC
    );
    static final FunctionDescriptor plist_from_bin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_from_bin$MH = RuntimeHelper.downcallHandle(
        "plist_from_bin",
        constants$27.plist_from_bin$FUNC
    );
    static final FunctionDescriptor plist_from_json$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_from_json$MH = RuntimeHelper.downcallHandle(
        "plist_from_json",
        constants$27.plist_from_json$FUNC
    );
    static final FunctionDescriptor plist_from_openstep$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_from_openstep$MH = RuntimeHelper.downcallHandle(
        "plist_from_openstep",
        constants$27.plist_from_openstep$FUNC
    );
}


