// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final FunctionDescriptor plist_dict_get_item_key$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_dict_get_item_key$MH = RuntimeHelper.downcallHandle(
        "plist_dict_get_item_key",
        constants$22.plist_dict_get_item_key$FUNC
    );
    static final FunctionDescriptor plist_dict_get_item$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_dict_get_item$MH = RuntimeHelper.downcallHandle(
        "plist_dict_get_item",
        constants$22.plist_dict_get_item$FUNC
    );
    static final FunctionDescriptor plist_dict_item_get_key$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_dict_item_get_key$MH = RuntimeHelper.downcallHandle(
        "plist_dict_item_get_key",
        constants$22.plist_dict_item_get_key$FUNC
    );
    static final FunctionDescriptor plist_dict_set_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_dict_set_item$MH = RuntimeHelper.downcallHandle(
        "plist_dict_set_item",
        constants$22.plist_dict_set_item$FUNC
    );
    static final FunctionDescriptor plist_dict_remove_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_dict_remove_item$MH = RuntimeHelper.downcallHandle(
        "plist_dict_remove_item",
        constants$22.plist_dict_remove_item$FUNC
    );
    static final FunctionDescriptor plist_dict_merge$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_dict_merge$MH = RuntimeHelper.downcallHandle(
        "plist_dict_merge",
        constants$22.plist_dict_merge$FUNC
    );
}


