// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$35 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$35() {}
    static final FunctionDescriptor idevice_disconnect$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle idevice_disconnect$MH = RuntimeHelper.downcallHandle(
        "idevice_disconnect",
        constants$35.idevice_disconnect$FUNC
    );
    static final FunctionDescriptor idevice_connection_send$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle idevice_connection_send$MH = RuntimeHelper.downcallHandle(
        "idevice_connection_send",
        constants$35.idevice_connection_send$FUNC
    );
    static final FunctionDescriptor idevice_connection_receive_timeout$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle idevice_connection_receive_timeout$MH = RuntimeHelper.downcallHandle(
        "idevice_connection_receive_timeout",
        constants$35.idevice_connection_receive_timeout$FUNC
    );
    static final FunctionDescriptor idevice_connection_receive$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle idevice_connection_receive$MH = RuntimeHelper.downcallHandle(
        "idevice_connection_receive",
        constants$35.idevice_connection_receive$FUNC
    );
    static final FunctionDescriptor idevice_connection_enable_ssl$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle idevice_connection_enable_ssl$MH = RuntimeHelper.downcallHandle(
        "idevice_connection_enable_ssl",
        constants$35.idevice_connection_enable_ssl$FUNC
    );
    static final FunctionDescriptor idevice_connection_disable_ssl$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle idevice_connection_disable_ssl$MH = RuntimeHelper.downcallHandle(
        "idevice_connection_disable_ssl",
        constants$35.idevice_connection_disable_ssl$FUNC
    );
}


