// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final FunctionDescriptor plist_array_item_remove$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_array_item_remove$MH = RuntimeHelper.downcallHandle(
        "plist_array_item_remove",
        constants$21.plist_array_item_remove$FUNC
    );
    static final FunctionDescriptor plist_array_new_iter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_array_new_iter$MH = RuntimeHelper.downcallHandle(
        "plist_array_new_iter",
        constants$21.plist_array_new_iter$FUNC
    );
    static final FunctionDescriptor plist_array_next_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_array_next_item$MH = RuntimeHelper.downcallHandle(
        "plist_array_next_item",
        constants$21.plist_array_next_item$FUNC
    );
    static final FunctionDescriptor plist_dict_get_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_dict_get_size$MH = RuntimeHelper.downcallHandle(
        "plist_dict_get_size",
        constants$21.plist_dict_get_size$FUNC
    );
    static final FunctionDescriptor plist_dict_new_iter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_dict_new_iter$MH = RuntimeHelper.downcallHandle(
        "plist_dict_new_iter",
        constants$21.plist_dict_new_iter$FUNC
    );
    static final FunctionDescriptor plist_dict_next_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle plist_dict_next_item$MH = RuntimeHelper.downcallHandle(
        "plist_dict_next_item",
        constants$21.plist_dict_next_item$FUNC
    );
}


