// Generated by jextract

package libim;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     enum idevice_event_type event;
 *     char* udid;
 *     enum idevice_connection_type conn_type;
 * };
 * }
 */
public class idevice_event_t {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("event"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("udid"),
        Constants$root.C_INT$LAYOUT.withName("conn_type"),
        MemoryLayout.paddingLayout(32)
    );
    public static MemoryLayout $LAYOUT() {
        return idevice_event_t.$struct$LAYOUT;
    }
    static final VarHandle event$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("event"));
    public static VarHandle event$VH() {
        return idevice_event_t.event$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enum idevice_event_type event;
     * }
     */
    public static int event$get(MemorySegment seg) {
        return (int)idevice_event_t.event$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enum idevice_event_type event;
     * }
     */
    public static void event$set(MemorySegment seg, int x) {
        idevice_event_t.event$VH.set(seg, x);
    }
    public static int event$get(MemorySegment seg, long index) {
        return (int)idevice_event_t.event$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void event$set(MemorySegment seg, long index, int x) {
        idevice_event_t.event$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle udid$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("udid"));
    public static VarHandle udid$VH() {
        return idevice_event_t.udid$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* udid;
     * }
     */
    public static MemorySegment udid$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)idevice_event_t.udid$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* udid;
     * }
     */
    public static void udid$set(MemorySegment seg, MemorySegment x) {
        idevice_event_t.udid$VH.set(seg, x);
    }
    public static MemorySegment udid$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)idevice_event_t.udid$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void udid$set(MemorySegment seg, long index, MemorySegment x) {
        idevice_event_t.udid$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle conn_type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("conn_type"));
    public static VarHandle conn_type$VH() {
        return idevice_event_t.conn_type$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enum idevice_connection_type conn_type;
     * }
     */
    public static int conn_type$get(MemorySegment seg) {
        return (int)idevice_event_t.conn_type$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enum idevice_connection_type conn_type;
     * }
     */
    public static void conn_type$set(MemorySegment seg, int x) {
        idevice_event_t.conn_type$VH.set(seg, x);
    }
    public static int conn_type$get(MemorySegment seg, long index) {
        return (int)idevice_event_t.conn_type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void conn_type$set(MemorySegment seg, long index, int x) {
        idevice_event_t.conn_type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


